import Foundation

/*
let perfumeDataArray: [Perfume] = [
    Perfume(name: "Cool Water", brand: "Davidoff", year: "1996.0", topNotes: ["melon", "lotus", "lemon", "pineapple", "quince", "calone", "lily", "black currant"], middleNotes: ["lotus", "water lily", "lily-of-the-valley", "jasmine", "honey", "hawthorn", "rose"], baseNotes: ["musk", "vetiver", "violet root", "raspberry", "blackberry", "peach", "sandalwood", "vanilla"], mainAccords: ["Fresh": 1.0, "Floral": 0.8, "Fruity": 0.7, "Aquatic": 0.5, "Ozonic": 0.4], isFavorite: false),
    Perfume(name: "Dkny Be Delicious", brand: "Donna Karan", year: "2004.0", topNotes: ["cucumber", "grapefruit", "magnolia"], middleNotes: ["green apple", "lily-of-the-valley", "tuberose", "violet", "rose"], baseNotes: ["woodsy notes", "sandalwood", "amber"], mainAccords: ["Green": 1.0, "Fruity": 0.8, "Aquatic": 0.7, "Ozonic": 0.5, "Fresh": 0.4], isFavorite: false),
    Perfume(name: "Flower By Kenzo", brand: "Kenzo", year: "2000.0", topNotes: ["bulgarian rose", "hawthorn", "black currant", "mandarin orange"], middleNotes: ["parma violet", "rose", "opoponax", "jasmine"], baseNotes: ["vanilla", "white musk", "incense"], mainAccords: ["Powdery": 1.0, "Floral": 0.8, "Violet": 0.7, "Rose": 0.5, "Amber": 0.4], isFavorite: false),
    Perfume(name: "Chanel No 5 Parfum", brand: "Chanel", year: "1921.0", topNotes: ["aldehydes", "ylang-ylang", "neroli", "bergamot", "lemon"], middleNotes: ["iris", "jasmine", "rose", "orris root", "lily-of-the-valley"], baseNotes: ["civet", "musk", "sandalwood", "amber", "moss", "vanilla", "vetiver", "patchouli"], mainAccords: ["Powdery": 1.0, "Woody": 0.8, "Aldehydic": 0.7, "Iris": 0.5, "Fresh": 0.4], isFavorite: false),
    Perfume(name: "Bright Crystal", brand: "Versace", year: "2006.0", topNotes: ["yuzu", "pomegranate", "ice"], middleNotes: ["peony", "lotus", "magnolia"], baseNotes: ["musk", "mahogany", "amber"], mainAccords: ["Floral": 1.0, "Citrus": 0.8, "Fresh": 0.7, "Woody": 0.5, "Fresh Spicy": 0.4], isFavorite: true),
    Perfume(name: "Prada Candy", brand: "Prada", year: "2011.0", topNotes: ["caramel"], middleNotes: ["powdery notes", "musk"], baseNotes: ["benzoin", "vanilla"], mainAccords: ["Caramel": 1.0, "Powdery": 0.8, "Amber": 0.7, "Sweet": 0.5, "Vanilla": 0.4], isFavorite: true),
    Perfume(name: "J Adore", brand: "Dior", year: "1999.0", topNotes: ["pear", "melon", "magnolia", "peach", "mandarin orange", "bergamot"], middleNotes: ["jasmine", "lily-of-the-valley", "tuberose", "freesia", "rose", "orchid", "plum", "violet"], baseNotes: ["musk", "vanilla", "blackberry", "cedar"], mainAccords: ["White Floral": 1.0, "Floral": 0.8, "Fruity": 0.7, "Sweet": 0.5, "Fresh": 0.4]),
    Perfume(name: "D G Anthology L Imperatrice 3", brand: "Dolce Gabbana", year: "2009.0", topNotes: ["kiwi", "rhuburb", "pink pepper"], middleNotes: ["watermelon", "cyclamen", "jasmine"], baseNotes: ["lemon tree", "musk", "sandalwood"], mainAccords: ["Fruity": 1.0, "Ozonic": 0.8, "Aquatic": 0.7, "Green": 0.5, "Sweet": 0.4]),
    Perfume(name: "MYSLF Eau de Parfum", brand: "Yves Saint Laurent", year: "2023", topNotes: ["calabrian bergamot", "bergamot"], middleNotes: ["tunisian orange blossom"], baseNotes: ["ambrofix", "patchouli"], mainAccords: ["Citrus": 1.0, "White Floral": 0.8, "Amber": 0.7, "Woody": 0.5, "Patchouli": 0.4], mlIdentifier: "YSlMyslf"),
    Perfume(name: "Club de nuit urban man elixir", brand: "Armaf", year: "2022", topNotes: ["pink pepper", "bergamot", "orange blossom", "jasmine"], middleNotes: ["lavender", "elemi", "geranium", "saffron", "tagetes", "vetiver"], baseNotes: ["ambroxan", "patchouli", "amber", "cedar", "labdanum"], mainAccords: ["Aromatic": 1.0, "Fresh Spicy": 0.8, "Amber": 0.7, "Woody": 0.5], mlIdentifier: "Clubdenuiturban man elixir")
]
*/

let perfumeDataArray: [Perfume] = [
    Perfume(name: "MYSLF Eau de Parfum", brand: "Yves Saint Laurent", year: "2023", topNotes: ["calabrian bergamot", "bergamot"], middleNotes: ["tunisian orange blossom"], baseNotes: ["ambrofix", "patchouli"], mainAccords: ["Citrus": 1.0, "White Floral": 0.83], mlIdentifier: "ysl myslf"),
    Perfume(name: "Nautica Voyage", brand: "Nautica", year: "2006", topNotes: ["apple", "green leaves"], middleNotes: ["lotus", "mimosa"], baseNotes: ["musk", "cedar", "oakmoss", "amber"], mainAccords: ["Green": 1.0, "Fruity": 0.64], mlIdentifier: "nautica voyage"),
    Perfume(name: "Club de Nuit Blue Iconic", brand: "Armaf", year: "2022", topNotes: ["grapefruit", "lemon", "mint", "pink pepper", "coriander"], middleNotes: ["ginger", "melon", "jasmine", "nutmeg"], baseNotes: ["sandalwood", "amber", "incense", "woody notes", "cedar", "patchouli", "labdanum"], mainAccords: ["Citrus": 1.0, "Woody": 0.93], mlIdentifier: "club de nuit iconic"),
    Perfume(name: "Allusion", brand: "Pandora", year: "2023", topNotes: ["orange", "sea notes", "aldehydes", "blood mandarin"], middleNotes: ["pepper", "neroli", "cedar"], baseNotes: ["tonka bean", "vanilla", "white musk", "amber", "vetiver", "elemi resin"], mainAccords: ["Citrus": 1.0, "Marine": 0.80], mlIdentifier: "pandora allusion"),
    Perfume(name: "Club de Nuit Intense Man", brand: "Armaf", year: "2015", topNotes: ["lemon", "pineapple", "bergamot", "black currant", "apple"], middleNotes: ["birch", "jasmine", "rose"], baseNotes: ["musk", "ambergris", "patchouli", "vanilla"], mainAccords: ["Citrus": 1.0, "Fruity": 0.71], mlIdentifier: "club de nuit intense man"),
    Perfume(name: "Eros", brand: "Versace", year: "2012", topNotes: ["mint", "green apple", "lemon"], middleNotes: ["tonka bean", "ambroxan", "geranium"], baseNotes: ["madagascar vanilla", "virginian cedar", "atlas cedar", "vetiver", "oakmoss"], mainAccords: ["Vanilla": 1.0, "Aromatic": 0.94], mlIdentifier: "versace eros"),
    Perfume(name: "Eros Flame", brand: "Versace", year: "2018", topNotes: ["mandarin orange", "black pepper", "chinotto", "lemon", "rosemary"], middleNotes: ["pepper", "geranium", "rose"], baseNotes: ["vanilla", "tonka bean", "sandalwood", "texas cedar", "patchouli", "oakmoss"], mainAccords: ["Citrus": 1.0, "Fresh Spicy": 0.71], mlIdentifier: "versace eros flame"),
    Perfume(name: "Club de Nuit Woman", brand: "Armaf", year: "2015", topNotes: ["orange", "grapefruit", "bergamot", "peach"], middleNotes: ["rose", "geranium", "jasmine", "litchi"], baseNotes: ["patchouli", "vanilla", "musk", "vetiver"], mainAccords: ["Citrus": 1.0, "Patchouli": 0.65], mlIdentifier: "club de nuit woman"),
    Perfume(name: "La Uno Intense Blue", brand: "Fragrance World", year: "2022", topNotes: ["grapefruit", "mandarin orange"], middleNotes: ["sea water", "juniper"], baseNotes: ["amberwood", "musk"], mainAccords: ["Citrus": 1.0, "Aromatic": 0.87], mlIdentifier: "launo intense blue"),
    Perfume(name: "Club de Nuit Urban Man Elixir", brand: "Armaf", year: "2022", topNotes: ["pink pepper", "bergamot", "orange blossom", "jasmine"], middleNotes: ["lavender", "elemi", "geranium", "saffron", "tagetes", "vetiver"], baseNotes: ["ambroxan", "patchouli", "amber", "cedar", "labdanum"], mainAccords: ["Amber": 1.0, "Aromatic": 0.81], mlIdentifier: "club de nuit urban man elixir")
]
